MyLibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

library/urls.py
from django.urls import path
from .views import index, about, add_book, book_list, book_detail, book_edit, book_delete

app_name = 'library'
urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('books/add/', add_book, name='add_book'),
    path('books/', book_list, name='book_list'),
    path('books/<slug:slug>/', book_detail, name='book_detail'),
    path('books/<slug:slug>/edit', book_edit, name='book_edit'),
    path('books/<slug:slug>/delete', book_delete, name='book_delete'),
]

mylibrary/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mylibrary import settings
from library.views import root


urlpatterns = [
    path('', root),
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "library.views.forbidden"
handler404 = "library.views.page_not_found"
handler500 = "library.views.server_error"

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out,
                    user_detail, change_password)
app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('log_in/', log_in, name='login'),
    path('log_out/', log_out, name='logout'),
    path('default/<int:pk>', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
]

library/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from slugify import slugify


User = get_user_model()


class Book(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Информация о книге")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Опубликовано", editable=False)
    file = models.FileField(upload_to='books/file/', blank=False, verbose_name="Файл (текст книги)")
    image = models.ImageField(upload_to='books/image/', blank=True, verbose_name="Изображение (обложка)")
    slug = models.SlugField(max_length=200, unique=True, editable=False, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('library:book_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"

    def __str__(self):
        return self.title

library/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        author = kwargs.pop('author', None)
        super(BookForm, self).__init__(*args, **kwargs)
        if author:
            self.fields['author'].initial = author
            self.fields['author'].disabled = True

    class Meta:
        model = Book
        fields = ['author', 'title', 'text', 'file', 'image']

library/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import BookForm
from .models import Book


def root(request):
    return render(request, template_name='library/index.html')


def index(request):
    return render(request, template_name='library/index.html')


def about(request):
    context = {
        'name': 'БиблиоЦентр',
        'email': 'bibliocentre@mail.ru',
        'phone': '+7 (999) 999-99-99',
        'address': 'м. Невский проспект',
        'title': "О сайте"
    }
    return render(request, template_name='library/about.html', context=context)


@login_required
def add_book(request):
    if request.method == "GET":
        form = BookForm(author=request.user)
        context = {
            'form': form,
            'title': "Добавление книги",
        }
        return render(request, template_name='library/add_book.html', context=context)

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, author=request.user)
        if form.is_valid():
            book = Book()
            book.author = form.cleaned_data['author']
            book.title = form.cleaned_data['title']
            book.text = form.cleaned_data['text']
            book.file = form.cleaned_data['file']
            book.image = form.cleaned_data['image']
            book.save()
        return index(request)


def book_list(request):
    books = Book.objects.all()
    context = {
        'title': "Книги",
        'books': books,
    }
    return render(request, template_name='library/books.html', context=context)


def book_detail(request, slug):
    book = Book.objects.get(slug=slug)
    context = {
        'title': "Информация о книге",
        'book': book,
    }
    return render(request, template_name='library/book_detail.html', context=context)


@login_required
def book_edit(request, slug):
    book = get_object_or_404(Book, slug=slug)
    # if book.author == request.user:
    user = request.user
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book, author=request.user)
        if form.is_valid():
            form.save()
            return book_list(request)
    else:
        form = BookForm(instance=book, author=request.user)
    context = {
            'form': form,
            'user': user,
            'title': "Редактировать характеристики книги",
    }
    return render(request, template_name='library/book_edit.html', context=context)

@login_required
def book_delete(request, slug):
    book = get_object_or_404(Book, slug=slug)
    if request.method == "POST":
        book.delete()
        return redirect("library:book_list")
    return render(request, template_name="library/book_delete.html", context={"book": book})


def forbidden(request, exception):
    return render(request, "library/403.html", status=403)


def page_not_found(request, exception):
    return render(request, "library/404.html", status=404)


def server_error(request):
    return render(request, "library/500.html", status=500)

library/templates/library/about.html
{% extends 'library/base.html' %} {% block content %}
{% load static %}
<h2>О нас</h2>
<div class="about_section">
<div class="row row-cols-1 row-cols-md-3 g-4" style="width: 80%;">
    <div class="col">
    <div class="card h-100">
      <img src="{% static 'img/about_2.jpg' %}" class="card-img-top" alt="КартинкаО1">
      <div class="card-body">
        <h5 class="card-title">Удобство</h5>
        <p class="card-text">Опубликуй или почитай книгу прямо из дома!</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img src="{% static 'img/about_1.png' %}" class="card-img-top" alt="КартинкаО2">
      <div class="card-body">
        <h5 class="card-title">Возможности</h5>
        <p class="card-text">В нашем сервисе можно опубликовать 1000 книг!</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img src="{% static 'img/about_3.jpg' %}" class="card-img-top" alt="КартинкаО3">
      <div class="card-body">
        <h5 class="card-title">Доступность</h5>
        <p class="card-text">Сервис абсолютно бесплатный</p>
      </div>
    </div>
  </div>

</div>
  </div>

<div class="about_section">
<div class="main__contacts">
  <section class="main__contacts__text">
    <p>Автор: {{name}}</p>
    <p>Email: {{email}}</p>
    <p>Телефон: {{phone}}</p>
    <p>Адрес: {{address}}</p>
  </section>
  <div style="position: relative; overflow: hidden">
    <a
      href="https://yandex.ru/maps/2/saint-petersburg/?utm_medium=mapframe&utm_source=maps"
      style="color: #eee; font-size: 12px; position: absolute; top: 0px"
      >Санкт‑Петербург</a
    ><a
      href="https://yandex.ru/maps/2/saint-petersburg/stops/station__9898637/?ll=30.379296%2C59.870206&tab=overview&utm_medium=mapframe&utm_source=maps&z=15"
      style="color: #eee; font-size: 12px; position: absolute; top: 14px"
      >Международная — Яндекс Карты</a
    ><iframe
      src="https://yandex.ru/map-widget/v1/?ll=30.379296%2C59.870206&masstransit%5BstopId%5D=station__9898637&mode=masstransit&tab=overview&z=15"
      width="560"
      height="350"
      frameborder="1"
      allowfullscreen="true"
      style="position: relative"
    ></iframe>
  </div>
</div>
</div>
{% endblock content %}

library/templates/library/add_book.html
{% extends 'library/base.html' %} {% block content %}
<h2 class="add_title">Опубликовать книгу</h2>
<section class="main__text">
  <form action="" method="post" enctype="multipart/form-data" class="form-send">
    {% csrf_token %}
		<div class="fields">
			{% for field in form %}
			<div class="text-field">
				<span class="text-field__label">{{field.label_tag}}</span>
				{{field}}
			</div>
			{% endfor %}
		<!-- {{ form.as_p }} это для отображения  в виде абзацов-->
</div>
    <button type="submit" class="btn btn-secondary send" >Опубликовать книгу</button>
  </form>
</section>

{% endblock content %}

library/templates/library/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
  </head>
  <body>
    <nav class="header">
      <div class="left">
        <a href="{% url 'library:index' %}"
          ><img src="{% static 'img/logo.png' %}" width="40px" alt="Иконка"
        /></a>
        <a href="{% url 'library:index' %}">Главная</a>
      </div>
      <div class="right" style="display: flex;">
        <a href="{% url 'library:about' %}">О сайте</a>
        <a href="{% url 'library:add_book' %}">Опубликовать книгу</a>
        <a href="{% url 'library:book_list' %}">Книги</a>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/people.png' %}" width="20px">
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              {% if not user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
            <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
            <li><hr class="dropdown-divider"></li>
              {% endif %}
              {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
            <li><a class="dropdown-item" href="{% url 'users:detail' pk=user.pk %}">{{ user.username }}</a></li>
              {% endif %}
          </ul>
              </div>
      </div>
    </nav>
    <section class="main">{% block content %}{% endblock content %}</section>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

library/templates/library/book_delete.html
{% extends 'library/base.html' %}
{% load static %}
{% block content %}
<div class="book_section">
<h1>Вы уверены, что хотите удалить эту книгу?</h1>
<h2 style="opacity: 1;">Информация о книге № {{book.id}}</h2>
<div class="card text-white bg-dark mb-3" style="width: 60%;">
  <div class="row g-0">
    <div class="col-md-3">
    {% if book.image %}
    <img
      src="{{book.image.url}}"
      class="img-fluid rounded-start"
      alt="Обложка книги"
      style="width: 100%; height: 100%; object-fit: cover; border: 1px solid rgba(0, 0, 0, 0.175)"
    />
    {% else %}
    <img
      src="{% static 'img/no_image.png' %}"
      class="img-fluid rounded-start"
      alt="Обложка книги"
      style="width: 100%; height: 100%; object-fit: cover; border: 1px solid rgba(0, 0, 0, 0.175)"
    />
    {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card-header">
        {{book.author}}</div>
      <div class="card-body">
        <h5 class="card-title">{{book.title}}</h5>
        <p class="card-text" style="margin: 0;">Описание книги:</p>
        <p class="card-text" style="margin: 0;">{{book.text}}</p>
      </div>
      <div class="card-footer book_data">{{book.created_at}}</div>
    </div>
  </div>
</div>
<form method="post" style="display: block;" align="center">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'library:book_list'%}">
        <button type="button" class="btn btn-secondary">Отменить</button>
    </a>

</form>

{% endblock content %}

library/templates/library/book_detail.html
{% extends 'library/base.html' %}
{% load static %}
{% block content %}
<div class="book_section">
<h2 style="opacity: 1;">Информация о книге № {{book.id}}</h2>
<div class="card text-white bg-dark mb-3" style="width: 60%;">
  <div class="row g-0">
    <div class="col-md-3">
    {% if book.image %}
    <img
      src="{{book.image.url}}"
      class="img-fluid rounded-start"
      alt="Обложка книги"
      style="width: 100%; height: 100%; object-fit: cover; border: 1px solid rgba(0, 0, 0, 0.175)"
    />
    {% else %}
    <img
      src="{% static 'img/no_image.png' %}"
      class="img-fluid rounded-start"
      alt="Обложка книги"
      style="width: 100%; height: 100%; object-fit: cover; border: 1px solid rgba(0, 0, 0, 0.175)"
    />
    {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card-header">
        {{book.author}}</div>
      <div class="card-body">
        <h5 class="card-title">{{book.title}}</h5>
        <p class="card-text" style="margin: 0;">Описание книги:</p>
        <p class="card-text" style="margin: 0;">{{book.text}}</p>
      </div>
      <div class="card-footer book_data">{{book.created_at}}</div>
    </div>
  </div>
</div>

    {% if book.file %}
        <a href='{{book.file.url}}'>Посмотреть текст книги</a>
    {% else %}
        <p>Ссылка на скачивание исчезла :(</p>
    {% endif %}
<br />

{% if user == book.author %}
    <div>
  <a
    href="{% url 'library:book_edit' slug=book.slug %}"
    class="btn btn-secondary"
    >Редактировать</a
  >
  <form
    action="{% url 'library:book_delete' slug=book.slug %}"
    method="get"
    style="display: inline"
  >
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
  </form>
</div>
{% endif %}
  </div>
{% endblock content %}

library/templates/library/book_edit.html
{% extends 'library/base.html' %} {% block content %}
<h2>Редактировать книгу</h2>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-secondary" style="margin-bottom: 20px">Редактировать книгу</button>
</form>

{% endblock content %}

library/templates/library/books.html
{% extends 'library/base.html' %}
{% load static %}
{% block content %}

<h2>Книги</h2>
<section
  class="d-inline-flex justify-content-evenly flex-wrap w-75"
  style="gap: 20px; margin: 20px"
>
  {% for book in books %}
  <div class="card text-white bg-dark" style="width: 300px; height: 400px">
    {% if book.image %}
    <img
      src="{{book.image.url}}"
      class="card-img-top"
      alt="Обложка книги"
      style="width: 100%; height: 200px; object-fit: cover"
    />
    {% else %}
    <img
      src="{% static 'img/no_image.png' %}"
      class="card-img-top"
      alt="Обложка книги"
      style="width: 100%; height: 200px; object-fit: cover"
    />
    {% endif %}
    <div class="card-header" >
        <p class="card-text">{{book.author}}</p>
      </div>
    <div class="card-body" style="position: relative">
      <h5 class="card-title">{{book.title}}</h5>
      <p class="card-text text-min">{{book.text}}</p>
      <a
        href="{{ book.get_absolute_url }}"
        class="btn btn-secondary"
        style="position: absolute; bottom: 5%"
        >Подробнее</a
      >
    </div>
  </div>
  {% endfor %}
</section>
{% endblock content %}

library/templates/library/index.html
{% extends 'library/base.html' %} {% block content %}
<div class="main__index">
  <h2 class="main__index__title">Опубликуй свою книгу!</h2>
</div>
<div class="main__tittle">
  <p>Простота и легкость - наш девиз!</p>
</div>
<div class="main__info">
  <secton class="main__info__min">
			<p class="main__info__min__circle">1</p>
			<p class="main__info__min__text">Перейди на вкладку 'Добавить книгу'</p>
	</secton>
  <secton class="main__info__min">
			<p class="main__info__min__circle">2</p>
			<p class="main__info__min__text">Введи необходимые данные</p>
	</secton>
  <secton class="main__info__min">
			<p class="main__info__min__circle">3</p>
			<p class="main__info__min__text">Нажми на кнопку 'Опубликовать книгу'</p>
	</secton>
</div>
<a href="{% url 'library:add_book' %}" class="book_slk">Перейти к созданию книги</a>


{% endblock content %}