MyLibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

library/urls.py
from django.urls import path
from .views import index, about, add_book, book_list, book_detail, book_edit, book_delete

app_name = 'library'
urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('books/add/', add_book, name='add_book'),
    path('books/', book_list, name='book_list'),
    path('books/<slug:slug>/', book_detail, name='book_detail'),
    path('books/<slug:slug>/edit', book_edit, name='book_edit'),
    path('books/<slug:slug>/delete', book_delete, name='book_delete'),
]

mylibrary/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mylibrary import settings
from library.views import root


urlpatterns = [
    path('', root),
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "library.views.forbidden"
handler404 = "library.views.page_not_found"
handler500 = "library.views.server_error"

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out,
                    user_detail, change_password)
app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('log_in/', log_in, name='login'),
    path('log_out/', log_out, name='logout'),
    path('default/<int:pk>', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
]

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    city = models.CharField(max_length=100, verbose_name="Город")
    image = models.ImageField(upload_to="users/", null=True, verbose_name="Изображение")

users/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class UserRegistrationForm(forms.ModelForm):

    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    def clean_password2(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['password'] != cleaned_data['password2']:
            raise forms.ValidationError('Пароли не совпадают!')
        return cleaned_data['password2']

    class Meta:
        model = User
        fields = ('username', 'password',
                  'first_name', 'last_name', 'email',
                  'phone', 'city')


class CustomPasswordChangeForm(forms.Form):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput)
    new_password_1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput)
    new_password_2 = forms.CharField(label="Повторите новый пароль", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data["old_password"]
        new_password_1 = cleaned_data["new_password_1"]
        new_password_2 = cleaned_data["new_password_2"]

        if new_password_1 and new_password_2 and new_password_1 != new_password_2:
            raise forms.ValidationError('Пароли не совпадают!')

        if new_password_1 and new_password_2 and new_password_1 == new_password_2 and old_password == new_password_1:
            raise forms.ValidationError('Пароль совпадает с текущим!')

        return cleaned_data

users/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404

from django.contrib.auth import update_session_auth_hash
from mylibrary.settings import LOGIN_REDIRECT_URL
from .forms import UserRegistrationForm, CustomPasswordChangeForm


User = get_user_model()


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            context = {
                'title': 'Успешная регистрация',
                'new_user': new_user,
            }
            return render(request, template_name='users/register_done.html', context=context)
    user_form = UserRegistrationForm()
    context = {
        'title': 'Регистрация',
        'register_form': user_form,
    }
    return render(request, template_name='users/register.html', context=context)


def log_in(request):
    form = AuthenticationForm(request, request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            url = request.GET.get('next', LOGIN_REDIRECT_URL)
            return redirect(url)
    context = {'form': form}
    return render(request, template_name='users/login.html', context=context)


def log_out(request):
    logout(request)
    return redirect('library:index')


def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.user != user:
        raise PermissionDenied()
    context = {
        'user': user,
        'title': 'Информация о профиле',
    }
    return render(request, template_name='users/profile.html', context=context)



@login_required
def change_password(request):
    if request.method == "POST":
        form = CustomPasswordChangeForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password_1']

            if request.user.check_password(old_password):
                request.user.set_password(new_password)
                request.user.save()
                update_session_auth_hash(request, request.user)
                return redirect('library:index')
            else:
                form.add_error('old_password', 'Старый пароль неверный!')
                return redirect('users:change_password')

        return redirect('users:change_password')

    else:
        form = CustomPasswordChangeForm()
        context = {
            'title': 'Сменить пароль',
            'form': form,
        }
        return render(request, template_name='users/change_password.html', context=context)

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
  </head>
  <body>
    <nav class="header">
      <div class="left">
        <a href="{% url 'library:index' %}"
          ><img src="{% static 'img/logo.png' %}" width="40px" alt="Иконка"
        /></a>
        <a href="{% url 'library:index' %}">Главная</a>
      </div>
      <div class="right" style="display: flex;">
        <a href="{% url 'library:about' %}">О сайте</a>
        <a href="{% url 'library:add_book' %}">Опубликовать книгу</a>
        <a href="{% url 'library:book_list' %}">Книги</a>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/people.png' %}" width="20px">
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
              {% if not user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
            <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
            <li><hr class="dropdown-divider"></li>
              {% endif %}
              {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
            <li><a class="dropdown-item" href="{% url 'users:detail' pk=user.pk %}">{{ user.username }}</a></li>
              {% endif %}
          </ul>
              </div>
      </div>
    </nav>
    <section class="main">{% block content %}{% endblock content %}</section>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

users/templates/users/change_password.html
{% extends 'users/base.html' %}
{% block content %}
<div class="password_section">
<form method="post">
    {% csrf_token %}
    <div class="fields">
		{% for field in form %}
		<div class="text-field">
			<span class="text-field__label">{{field.label_tag}}</span>
			{{field}}
        </div>
        {% if field.errors %}
        <span>Исправьте ошибки в поле:</span>
        <div class="error-list">
            <ul>
                {% for error in field.errors %}
                <li>{{error}}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endfor %}

        <button type="submit" class="btn btn-secondary" style="margin: 20px 0;">Изменить</button>
        </div>
</form>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% block content %}
<div class="login_section">
    <h2>Пожалуйста, войдите на сайт</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-secondary">Войти</button>
</form>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% block content %}
{% load static %}
<div class="profile_section">
<h2>Ваш профиль</h2>
<div class="container_profile">
<div class="profile_row">
<img src="{% static 'img/profile.jpg' %}" style="width: 150px;" alt="Профильное фото"/>
<h5>{{ user.username }}</h5>
</div>
<div class="profile_row">
<div class="profile-work">
<p>Доступные действия:</p>
<a href="{% url 'library:add_book' %}">Опубликовать книгу</a><br/>
<a href="{% url 'library:book_list' %}">Посмотреть книги</a><br/>
<a href="{% url 'users:change_password' %}">Изменить пароль</a><br/>
<a href="{% url 'users:logout' %}">Выйти</a><br/>
</div>

<div>
<div class="tab-content profile-tab">
<div class="tab-pane fade show active" aria-labelledby="home-tab">
<div class="row">
<div class="col-md-6">
 <label>Никнейм</label>
</div>
<div class="col-md-6">
<p>{{ user.username }}</p>
</div>
</div>
<div class="row">
 <div class="col-md-6">
<label>Фамилия Имя</label>
</div>
<div class="col-md-6">
  <p>{{ user.last_name }} {{ user.first_name }}</p>
</div>
</div>
<div class="row">
<div class="col-md-6">
<label>Почта</label>
</div>
<div class="col-md-6">
<p>{{ user.email }}</p>
</div>
</div>
<div class="row">
<div class="col-md-6">
<label>Телефон</label>
</div>
<div class="col-md-6">
<p>{{ user.phone }}</p>
</div>
</div>
<div class="row">
<div class="col-md-6">
<label>Город</label>
</div>
<div class="col-md-6">
<p>{{ user.city }}</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% block content %}

<h2>Регистрация пользователя</h2>
<form method="post" class="register_form">
    {% csrf_token %}
    		{% for field in register_form %}
		<div class="text-field">
			<span class="text-field__label">{{field.label_tag}}</span>
			{{field}}
    </div>
        {% endfor %}

    <button type="submit" class="btn btn-secondary" style="margin: 20px 0;">Зарегистрироваться</button>
</form>

{% endblock content %}

users/templates/users/register_done.html
{% extends 'users/base.html' %}
{% block content %}
<div class="done_section">
<h2> Пользователь {{ new_user.username }} успешно зарегистрирован! </h2>
   <a href="{% url 'users:login' %}"><button type="button" class="btn btn-secondary" >Войти в свой аккаунт</button></a>
</div>
{% endblock content %}